services:
  weight-tracker:
    build:
      context: .
      # Quitamos la línea 'dockerfile: Dockerfile', Docker buscará el archivo por defecto
      args:
        VITE_SUPABASE_URL: "https://anvrbqvdswjexseirxhb.supabase.co"
        VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFudnJicXZkc3dqZXhzZWlyeGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1NDIwMDYsImV4cCI6MjA4MTExODAwNn0.6OStsGMiRnhP4f0xj_Gj54KaUh2HbDEBmLAO2kGXG04"
    container_name: weight-tracker
    restart: always
    ports:
      - "8080:80"